vim.g.mapleader = ';'

require'sinclair/sets'
require'sinclair/plugins'
require'sinclair/lsp'
require'sinclair/treesitter'
require'sinclair/telescope'
require'sinclair/explorer'
require'sinclair/git'
require'sinclair/keymaps'
require'sinclair/autocmds'
require'sinclair/commands'
require'sinclair/debugger'
require'sinclair/jsx'
